In [5]:
from mxnet import nd

In [16]:
def f(a):
    b = a * 2
    while b.norm().asscalar() <1000:
        b = b *2
    if b.sum().asscalar() >0:
        c = b
    else:
        c = 100*b
    return c

a = nd.random.normal(shape=1)
print(a)
a.attach_grad()
with autograd.record():
    c = f(a)

c.backward()
print(a.grad)



[1.1839255]
<NDArray 1 @cpu(0)>

[1024.]
<NDArray 1 @cpu(0)>
1024.0


In [2]:

aram_w = nd.random.normal(0, 1, shape=(1,2))
param_b = nd.random_normal(0,1, shape=(1,))


In [3]:
print(aram_w, param_b)


[[2.2122064 0.7740038]]
<NDArray 1x2 @cpu(0)> 
[1.0434403]
<NDArray 1 @cpu(0)>


In [26]:
v=nd.random_normal(3, 1, shape=(3,1))
print(v)
t = v.T
print(t)
v+t.reshape(v.shape)


[[2.9773827]
 [3.574614 ]
 [4.4661264]]
<NDArray 3x1 @cpu(0)>

[[2.9773827 3.574614  4.4661264]]
<NDArray 1x3 @cpu(0)>



[[5.9547653]
 [7.149228 ]
 [8.932253 ]]
<NDArray 3x1 @cpu(0)>

In [30]:
param_w = nd.random.normal(0, 1, shape=(1,2))
param_b = nd.random_normal(0,1, shape=(1,))
params = [param_w, param_b]
print(param_w, param_b)
for param in params:
  param *=2
print(param_w, param_b)


[[-1.0730928 -1.0424827]]
<NDArray 1x2 @cpu(0)> 
[-1.3278849]
<NDArray 1 @cpu(0)>

[[-2.1461856 -2.0849655]]
<NDArray 1x2 @cpu(0)> 
[-2.6557698]
<NDArray 1 @cpu(0)>


In [32]:
v = nd.arange(0,10)
o = nd.shuffle(v)
print(o)


[7. 5. 9. 2. 1. 3. 6. 0. 8. 4.]
<NDArray 10 @cpu(0)>


In [2]:
# 匿名函数
def act(x, y, transform=None):
    if not transform:
        return x, y
    else:
        return transform(x, y)
    
x, y = 2,4

print(act(2,4))
print(act(x,y, lambda x,y: (x + 100, y+10)))

(2, 4)
(102, 14)


In [9]:
y = nd.random.normal(shape=(3,2,1))
print(y.shape)

y2 = y.squeeze(axis=-1)
print(y2.shape)

(3, 2, 1)
(3, 2)
