In [1]:
from mxnet import nd


In [2]:
pred= nd.random.uniform(0, 10 ,shape=(10, 4))
print(pred)


[[5.4881353  5.928446   7.1518936  8.442657  ]
 [6.0276337  8.579456   5.448832   8.472517  ]
 [4.236548   6.235637   6.458941   3.8438172 ]
 [4.375872   2.975346   8.91773    0.5671298 ]
 [9.636627   2.726563   3.834415   4.7766514 ]
 [7.9172506  8.121687   5.288949   4.799772  ]
 [5.6804457  3.927848   9.255966   8.360787  ]
 [0.7103605  3.3739617  0.87129295 6.481719  ]
 [0.20218399 3.6824155  8.326199   9.571551  ]
 [7.7815676  1.4035077  8.700122   8.700872  ]]
<NDArray 10x4 @cpu(0)>


In [3]:
y_idx = nd.random.randint(0, 4, shape=(10,))
print(y_idx)


[3 1 1 3 3 1 1 0 2 3]
<NDArray 10 @cpu(0)>


In [5]:
y1=nd.exp(pred)
y1.sum(axis=1)



[ 6534.7686 10749.967   1264.8826  7564.     15495.853   6430.529
 15086.766    686.7113 18522.312  14411.893 ]
<NDArray 10 @cpu(0)>

In [15]:
h = (nd.sum(nd.exp(pred), axis=1))
h = nd.reshape(h, shape=(10,1))
h.shape

h2 = y1/h
h2.sum(axis=1)

h2


[[3.7002977e-02 5.7472631e-02 1.9534294e-01 7.1018147e-01]
 [3.8579885e-02 4.9499798e-01 2.1626715e-02 4.4479540e-01]
 [5.4683860e-02 4.0369430e-01 5.0469875e-01 3.6923122e-02]
 [1.0511522e-02 2.5907464e-03 9.8666465e-01 2.3310406e-04]
 [9.8836768e-01 9.8608830e-04 2.9857249e-03 7.6605133e-03]
 [4.2674807e-01 5.2354872e-01 3.0811632e-02 1.8891554e-02]
 [1.9426299e-02 3.3670273e-03 6.9377542e-01 2.8343123e-01]
 [2.9629988e-03 4.2512707e-02 3.4803548e-03 9.5104396e-01]
 [6.6086410e-05 2.1456433e-03 2.2301130e-01 7.7477700e-01]
 [1.6625352e-01 2.8236746e-04 4.1657570e-01 4.1688845e-01]]
<NDArray 10x4 @cpu(0)>

In [16]:
pred_idx = nd.argmax(h2, axis=1)
pred_idx


[3. 1. 2. 2. 0. 1. 2. 3. 3. 3.]
<NDArray 10 @cpu(0)>

In [23]:
# cross entropy
H = h2[nd.arange(10), y_idx]
cross_entropy = - nd.log(H)
print(cross_entropy)


[0.34223473 0.7032016  0.90709734 8.364026   4.8716764  0.6471252
 5.693725   5.821553   1.5005329  0.8749366 ]
<NDArray 10 @cpu(0)>


In [29]:
#accuracy
cmp = pred_idx.astype(y_idx.dtype) == y_idx
print(cmp, cmp.shape)
float(cmp.sum().asscalar())/float(len(cmp))


[1 1 0 0 0 1 0 0 0 1]
<NDArray 10 @cpu(0)> (10,)


0.4